### ISSUE TITLE
Old httpx installed with micromamba, manual upgrade was needed

### ISSUE THREAD

**Issue by astrojuanlu** [conda-forge/airflow-feedstock#121]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

After `micromamba install -c conda-forge airflow` on a clean Python 3.10 environment, I got an httpx version that was too old, and this made `airflow standalone` fail:

```
❯ airflow standalone                                                                                                               (airflow310) 
standalone | Starting Airflow Standalone
standalone | Checking database is initialized
Traceback (most recent call last):
  File "/Users/juan_cano/.micromamba/envs/airflow310/bin/airflow", line 11, in <module>
    sys.exit(main())
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/__main__.py", line 59, in main
    args.func(args)
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/cli/commands/standalone_command.py", line 51, in entrypoint
    StandaloneCommand().run()
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/cli/commands/standalone_command.py", line 67, in run
    self.initialize_database()
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/cli/commands/standalone_command.py", line 177, in initialize_database
    db.initdb()
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/utils/db.py", line 739, in initdb
    _create_db_from_orm(session=session)
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/utils/db.py", line 713, in _create_db_from_orm
    from airflow.auth.managers.fab.models import Model
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/airflow/auth/managers/fab/models/__init__.py", line 27, in <module>
    from flask_appbuilder.models.sqla import Model
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/flask_appbuilder/api/__init__.py", line 24, in <module>
    from flask_appbuilder.models.sqla.interface import SQLAInterface
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/flask_appbuilder/models/sqla/interface.py", line 14, in <module>
    from flask_appbuilder.filemanager import FileManager, ImageManager
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/flask_appbuilder/filemanager.py", line 10, in <module>
    from wtforms import ValidationError
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/wtforms/__init__.py", line 1, in <module>
    from wtforms import validators
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/wtforms/validators.py", line 7, in <module>
    import email_validator
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/email_validator/__init__.py", line 6, in <module>
    import dns.resolver
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/dns/asyncquery.py", line 38, in <module>
    from dns.query import (
  File "/Users/juan_cano/.micromamba/envs/airflow310/lib/python3.10/site-packages/dns/query.py", line 130, in <module>
    class _HTTPTransport(httpx.HTTPTransport):
AttributeError: module 'httpx' has no attribute 'HTTPTransport'
```

Then I did a manual upgrade and this fixed the problem:

```
❯ micromamba install -c conda-forge airflow "httpx>=0.24"                                                                          (airflow310) 
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Transaction

  Prefix: /Users/juan_cano/.micromamba/envs/airflow310

  Updating specs:

   - airflow
   - httpx[version='>=0.24']


  Package     Version  Build         Channel           Size
─────────────────────────────────────────────────────────────
  Upgrade:
─────────────────────────────────────────────────────────────

  - httpx      0.12.1  py_0          conda-forge     Cached
  + httpx      0.25.0  pyhd8ed1ab_0  conda-forge       65kB

  Downgrade:
─────────────────────────────────────────────────────────────

  - httpcore    1.0.0  pyhd8ed1ab_0  conda-forge     Cached
  + httpcore   0.18.0  pyhd8ed1ab_0  conda-forge       45kB

  Summary:

  Upgrade: 1 packages
  Downgrade: 1 packages

  Total download: 110kB
```

### Installed packages

```shell
List of packages in environment: "/Users/juan_cano/.micromamba/envs/airflow310"

  Name                                    Version       Build               Channel    
─────────────────────────────────────────────────────────────────────────────────────────
  aiohttp                                 3.8.6         py310hd125d64_1     conda-forge
  aiosignal                               1.3.1         pyhd8ed1ab_0        conda-forge
  airflow                                 2.7.2         py310hbe9552e_0     conda-forge
  alembic                                 1.12.0        pyhd8ed1ab_0        conda-forge
  amqp                                    5.1.1         pyhd8ed1ab_0        conda-forge
  annotated-types                         0.6.0         pyhd8ed1ab_0        conda-forge
  anyio                                   4.0.0         pyhd8ed1ab_0        conda-forge
  apache-airflow                          2.7.2         py310hb6292c7_0     conda-forge
  apache-airflow-providers-common-sql     1.7.2         pyhd8ed1ab_0        conda-forge
  apache-airflow-providers-ftp            3.5.2         pyhd8ed1ab_0        conda-forge
  apache-airflow-providers-http           4.5.2         pyhd8ed1ab_0        conda-forge
  apache-airflow-providers-imap           3.3.2         pyhd8ed1ab_0        conda-forge
  apache-airflow-providers-sqlite         3.4.3         pyhd8ed1ab_0        conda-forge
  apispec                                 6.3.0         pyhd8ed1ab_0        conda-forge
  argcomplete                             3.1.2         pyhd8ed1ab_0        conda-forge
  argon2-cffi                             23.1.0        pyhd8ed1ab_0        conda-forge
  argon2-cffi-bindings                    21.2.0        py310h2aa6e3c_4     conda-forge
  arrow                                   1.3.0         pyhd8ed1ab_0        conda-forge
  asgiref                                 3.7.2         pyhd8ed1ab_0        conda-forge
  async-timeout                           4.0.3         pyhd8ed1ab_0        conda-forge
  atk-1.0                                 2.38.0        hcb7b3dd_1          conda-forge
  attrs                                   23.1.0        pyh71513ae_1        conda-forge
  babel                                   2.13.0        pyhd8ed1ab_0        conda-forge
  backoff                                 2.2.1         pyhd8ed1ab_0        conda-forge
  backports                               1.0           pyhd8ed1ab_3        conda-forge
  backports.functools_lru_cache           1.6.5         pyhd8ed1ab_0        conda-forge
  backports.zoneinfo                      0.2.1         py310hbe9552e_8     conda-forge
  bcrypt                                  4.0.1         py310had9acf8_1     conda-forge
  billiard                                4.1.0         py310h2aa6e3c_1     conda-forge
  blinker                                 1.6.3         pyhd8ed1ab_0        conda-forge
  brotli-python                           1.1.0         py310h1253130_1     conda-forge
  brotlipy                                0.7.0         py310h2aa6e3c_1006  conda-forge
  bzip2                                   1.0.8         h3422bc3_4          conda-forge
  c-ares                                  1.20.1        h93a5062_0          conda-forge
  ca-certificates                         2023.7.22     hf0a4a13_0          conda-forge
  cachelib                                0.9.0         pyhd8ed1ab_0        conda-forge
  cairo                                   1.18.0        hd1e100b_0          conda-forge
  cattrs                                  23.1.2        pyhd8ed1ab_0        conda-forge
  celery                                  5.3.4         pyhd8ed1ab_1        conda-forge
  certifi                                 2023.7.22     pyhd8ed1ab_0        conda-forge
  cffi                                    1.16.0        py310hdcd7c05_0     conda-forge
  chardet                                 5.2.0         py310hbe9552e_1     conda-forge
  charset-normalizer                      3.3.0         pyhd8ed1ab_0        conda-forge
  click                                   8.1.7         unix_pyh707e725_0   conda-forge
  click-didyoumean                        0.3.0         pyhd8ed1ab_0        conda-forge
  click-plugins                           1.1.1         py_0                conda-forge
  click-repl                              0.3.0         pyhd8ed1ab_0        conda-forge
  clickclick                              20.10.2       pyhd8ed1ab_0        conda-forge
  colorama                                0.4.6         pyhd8ed1ab_0        conda-forge
  colorlog                                4.8.0         py310hbe9552e_3     conda-forge
  colour                                  0.1.5         py_0                conda-forge
  configupdater                           3.1.1         pyhd8ed1ab_0        conda-forge
  connexion                               2.14.2        pyhd8ed1ab_1        conda-forge
  cron-descriptor                         1.4.0         pyhd8ed1ab_0        conda-forge
  croniter                                2.0.1         pyhd8ed1ab_0        conda-forge
  cryptography                            41.0.4        py310hdd3b5e7_0     conda-forge
  deprecated                              1.2.14        pyh1a96a4e_0        conda-forge
  dill                                    0.3.7         pyhd8ed1ab_0        conda-forge
  dnspython                               2.4.2         pyhd8ed1ab_0        conda-forge
  docutils                                0.20.1        py310hbe9552e_2     conda-forge
  email-validator                         1.3.1         pyhd8ed1ab_0        conda-forge
  email_validator                         1.3.1         hd8ed1ab_0          conda-forge
  exceptiongroup                          1.1.3         pyhd8ed1ab_0        conda-forge
  expat                                   2.5.0         hb7217d7_1          conda-forge
  flask                                   2.2.5         pyhd8ed1ab_0        conda-forge
  flask-appbuilder                        4.3.6         pyhd8ed1ab_0        conda-forge
  flask-babel                             2.0.0         pyh9f0ad1d_0        conda-forge
  flask-caching                           2.1.0         pyhd8ed1ab_0        conda-forge
  flask-jwt-extended                      4.5.3         pyhd8ed1ab_0        conda-forge
  flask-limiter                           3.5.0         pyhd8ed1ab_0        conda-forge
  flask-login                             0.6.2         pyhd8ed1ab_1        conda-forge
  flask-session                           0.5.0         pyhd8ed1ab_0        conda-forge
  flask-sqlalchemy                        2.5.1         pyhd8ed1ab_0        conda-forge
  flask-wtf                               1.2.1         pyhd8ed1ab_0        conda-forge
  font-ttf-dejavu-sans-mono               2.37          hab24e00_0          conda-forge
  font-ttf-inconsolata                    3.000         h77eed37_0          conda-forge
  font-ttf-source-code-pro                2.038         h77eed37_0          conda-forge
  font-ttf-ubuntu                         0.83          hab24e00_0          conda-forge
  fontconfig                              2.14.2        h82840c6_0          conda-forge
  fonts-conda-ecosystem                   1             0                   conda-forge
  fonts-conda-forge                       1             0                   conda-forge
  freetype                                2.12.1        hadb7bae_2          conda-forge
  fribidi                                 1.0.10        h27ca646_0          conda-forge
  frozenlist                              1.4.0         py310h2aa6e3c_1     conda-forge
  furl                                    2.1.3         pyhd8ed1ab_0        conda-forge
  gdk-pixbuf                              2.42.10       h15fa40c_4          conda-forge
  gettext                                 0.21.1        h0186832_0          conda-forge
  giflib                                  5.2.1         h1a8c8d9_3          conda-forge
  google-re2                              1.1           py310h0caa01f_0     conda-forge
  googleapis-common-protos                1.61.0        pyhd8ed1ab_0        conda-forge
  graphite2                               1.3.13        h9f76cd9_1001       conda-forge
  graphviz                                8.1.0         h10878c0_0          conda-forge
  greenlet                                3.0.0         py310hd5a4765_1     conda-forge
  grpcio                                  1.59.1        py310h6121c79_0     conda-forge
  gtk2                                    2.24.33       h57013de_2          conda-forge
  gts                                     0.7.6         he42f4ea_4          conda-forge
  gunicorn                                21.2.0        py310hbe9552e_1     conda-forge
  h11                                     0.14.0        pyhd8ed1ab_0        conda-forge
  h2                                      4.1.0         pyhd8ed1ab_0        conda-forge
  harfbuzz                                8.2.1         hf1a6348_0          conda-forge
  hpack                                   4.0.0         pyh9f0ad1d_0        conda-forge
  hstspreload                             2023.1.1      pyhd8ed1ab_0        conda-forge
  httpcore                                0.18.0        pyhd8ed1ab_0        conda-forge
  httpx                                   0.25.0        pyhd8ed1ab_0        conda-forge
  hyperframe                              6.0.1         pyhd8ed1ab_0        conda-forge
  icu                                     73.2          hc8870d7_0          conda-forge
  idna                                    3.4           pyhd8ed1ab_0        conda-forge
  importlib-metadata                      6.8.0         pyha770c72_0        conda-forge
  importlib-resources                     6.1.0         pyhd8ed1ab_0        conda-forge
  importlib_resources                     6.1.0         pyhd8ed1ab_0        conda-forge
  infinity                                1.5           pyhd8ed1ab_0        conda-forge
  inflection                              0.5.1         pyh9f0ad1d_0        conda-forge
  intervals                               0.9.2         pyhd8ed1ab_0        conda-forge
  itsdangerous                            2.1.2         pyhd8ed1ab_0        conda-forge
  jinja2                                  3.1.2         pyhd8ed1ab_1        conda-forge
  jsonschema                              4.19.1        pyhd8ed1ab_0        conda-forge
  jsonschema-specifications               2023.7.1      pyhd8ed1ab_0        conda-forge
  kombu                                   5.3.2         py310hbe9552e_1     conda-forge
  lazy-object-proxy                       1.9.0         py310h2aa6e3c_1     conda-forge
  lerc                                    4.0.0         h9a09cb3_0          conda-forge
  libabseil                               20230802.1    cxx17_h13dd4ca_0    conda-forge
  libcxx                                  16.0.6        h4653b0c_0          conda-forge
  libdeflate                              1.19          hb547adb_0          conda-forge
  libexpat                                2.5.0         hb7217d7_1          conda-forge
  libffi                                  3.4.2         h3422bc3_5          conda-forge
  libgd                                   2.3.3         hfdf3952_9          conda-forge
  libglib                                 2.78.0        h24e9cb9_0          conda-forge
  libgrpc                                 1.59.1        hbcf6334_0          conda-forge
  libiconv                                1.17          he4db4b2_0          conda-forge
  libjpeg-turbo                           3.0.0         hb547adb_1          conda-forge
  libpng                                  1.6.39        h76d750c_0          conda-forge
  libprotobuf                             4.24.4        hc9861d8_0          conda-forge
  libre2-11                               2023.06.02    h1753957_0          conda-forge
  librsvg                                 2.56.3        h0db3404_0          conda-forge
  libsqlite                               3.43.2        h091b4b1_0          conda-forge
  libtiff                                 4.6.0         ha8a6c65_2          conda-forge
  libtool                                 2.4.7         hb7217d7_0          conda-forge
  libwebp                                 1.3.2         hf30222e_1          conda-forge
  libwebp-base                            1.3.2         hb547adb_0          conda-forge
  libxml2                                 2.11.5        h25269f3_1          conda-forge
  libzlib                                 1.2.13        h53f4e23_5          conda-forge
  limits                                  3.6.0         pyhd8ed1ab_0        conda-forge
  linkify-it-py                           2.0.0         pyhd8ed1ab_0        conda-forge
  lockfile                                0.12.2        py_1                conda-forge
  mako                                    1.2.4         pyhd8ed1ab_0        conda-forge
  markdown                                3.5           pyhd8ed1ab_0        conda-forge
  markdown-it-py                          3.0.0         pyhd8ed1ab_0        conda-forge
  markupsafe                              2.1.3         py310h2aa6e3c_1     conda-forge
  marshmallow                             3.20.1        pyhd8ed1ab_0        conda-forge
  marshmallow-oneofschema                 3.0.1         pyhd8ed1ab_0        conda-forge
  marshmallow-sqlalchemy                  0.26.1        pyhd8ed1ab_0        conda-forge
  mdit-py-plugins                         0.4.0         pyhd8ed1ab_0        conda-forge
  mdurl                                   0.1.0         pyhd8ed1ab_0        conda-forge
  multidict                               6.0.4         py310h8e9501a_1     conda-forge
  ncurses                                 6.4           h7ea286d_0          conda-forge
  openssl                                 3.1.3         h53f4e23_0          conda-forge
  opentelemetry-api                       1.16.0        pyhd8ed1ab_0        conda-forge
  opentelemetry-exporter-otlp             1.16.0        pyhd8ed1ab_0        conda-forge
  opentelemetry-exporter-otlp-proto-grpc  1.16.0        pyhd8ed1ab_0        conda-forge
  opentelemetry-exporter-otlp-proto-http  1.16.0        pyhd8ed1ab_0        conda-forge
  opentelemetry-proto                     1.16.0        pyhd8ed1ab_0        conda-forge
  opentelemetry-sdk                       1.16.0        pyhd8ed1ab_0        conda-forge
  opentelemetry-semantic-conventions      0.37b0        pyhd8ed1ab_0        conda-forge
  ordered-set                             4.1.0         pyhd8ed1ab_0        conda-forge
  orderedmultidict                        1.0.1         py_0                conda-forge
  packaging                               23.2          pyhd8ed1ab_0        conda-forge
  pango                                   1.50.14       hcf40dda_2          conda-forge
  passlib                                 1.7.4         pyh9f0ad1d_0        conda-forge
  pathspec                                0.11.2        pyhd8ed1ab_0        conda-forge
  pcre2                                   10.40         hb34f9b4_0          conda-forge
  pendulum                                2.1.2         py310h2aa6e3c_6     conda-forge
  phonenumbers                            8.13.22       pyhd8ed1ab_0        conda-forge
  pip                                     23.3          pyhd8ed1ab_0        conda-forge
  pixman                                  0.42.2        h13dd4ca_0          conda-forge
  pkgutil-resolve-name                    1.3.10        pyhd8ed1ab_1        conda-forge
  pluggy                                  1.3.0         pyhd8ed1ab_0        conda-forge
  prison                                  0.2.1         pyhd8ed1ab_0        conda-forge
  prompt-toolkit                          3.0.39        pyha770c72_0        conda-forge
  prompt_toolkit                          3.0.39        hd8ed1ab_0          conda-forge
  protobuf                                4.24.4        py310hc08086b_0     conda-forge
  psutil                                  5.9.5         py310h2aa6e3c_1     conda-forge
  pycparser                               2.21          pyhd8ed1ab_0        conda-forge
  pydantic                                2.4.2         pyhd8ed1ab_0        conda-forge
  pydantic-core                           2.10.1        py310had9acf8_0     conda-forge
  pygments                                2.16.1        pyhd8ed1ab_0        conda-forge
  pyjwt                                   2.8.0         pyhd8ed1ab_0        conda-forge
  pysocks                                 1.7.1         pyha2e5f31_6        conda-forge
  python                                  3.10.12       h01493a6_0_cpython  conda-forge
  python-daemon                           3.0.1         pyhd8ed1ab_1        conda-forge
  python-dateutil                         2.8.2         pyhd8ed1ab_0        conda-forge
  python-graphviz                         0.20.1        pyh22cad53_0        conda-forge
  python-nvd3                             0.15.0        pyh9f0ad1d_2        conda-forge
  python-slugify                          8.0.1         pyhd8ed1ab_2        conda-forge
  python-tzdata                           2023.3        pyhd8ed1ab_0        conda-forge
  python_abi                              3.10          4_cp310             conda-forge
  pytz                                    2023.3.post1  pyhd8ed1ab_0        conda-forge
  pytzdata                                2020.1        pyh9f0ad1d_0        conda-forge
  pyyaml                                  6.0.1         py310h2aa6e3c_1     conda-forge
  re2                                     2023.06.02    h6135d0a_0          conda-forge
  readline                                8.2           h92ec313_1          conda-forge
  referencing                             0.30.2        pyhd8ed1ab_0        conda-forge
  requests                                2.31.0        pyhd8ed1ab_0        conda-forge
  requests-toolbelt                       1.0.0         pyhd8ed1ab_0        conda-forge
  rfc3339-validator                       0.1.4         pyhd8ed1ab_0        conda-forge
  rfc3986                                 2.0.0         pyhd8ed1ab_0        conda-forge
  rich                                    13.6.0        pyhd8ed1ab_0        conda-forge
  rich-argparse                           1.3.0         pyhd8ed1ab_0        conda-forge
  rpds-py                                 0.10.6        py310hd442715_0     conda-forge
  setproctitle                            1.3.3         py310h2aa6e3c_0     conda-forge
  setuptools                              68.2.2        pyhd8ed1ab_0        conda-forge
  six                                     1.16.0        pyh6c4a22f_0        conda-forge
  sniffio                                 1.3.0         pyhd8ed1ab_0        conda-forge
  sqlalchemy                              1.4.49        py310hd125d64_1     conda-forge
  sqlalchemy-jsonfield                    1.0.1.post0   pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils                        0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-arrow                  0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-babel                  0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-base                   0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-color                  0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-encrypted              0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-intervals              0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-password               0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-pendulum               0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-phone                  0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-timezone               0.41.1        pyhd8ed1ab_0        conda-forge
  sqlalchemy-utils-url                    0.41.1        pyhd8ed1ab_0        conda-forge
  sqlparse                                0.4.4         pyhd8ed1ab_0        conda-forge
  tabulate                                0.9.0         pyhd8ed1ab_1        conda-forge
  tenacity                                8.2.3         pyhd8ed1ab_0        conda-forge
  termcolor                               2.3.0         pyhd8ed1ab_0        conda-forge
  text-unidecode                          1.3           pyhd8ed1ab_1        conda-forge
  tk                                      8.6.13        hb31c410_0          conda-forge
  types-python-dateutil                   2.8.19.14     pyhd8ed1ab_0        conda-forge
  typing-extensions                       4.8.0         hd8ed1ab_0          conda-forge
  typing_extensions                       4.8.0         pyha770c72_0        conda-forge
  tzdata                                  2023c         h71feb2d_0          conda-forge
  uc-micro-py                             1.0.1         pyhd8ed1ab_0        conda-forge
  unicodecsv                              0.14.1        py_1                conda-forge
  urllib3                                 2.0.6         pyhd8ed1ab_0        conda-forge
  vine                                    5.0.0         pyhd8ed1ab_1        conda-forge
  wcwidth                                 0.2.8         pyhd8ed1ab_0        conda-forge
  werkzeug                                2.2.3         pyhd8ed1ab_0        conda-forge
  wheel                                   0.41.2        pyhd8ed1ab_0        conda-forge
  wrapt                                   1.15.0        py310h2aa6e3c_1     conda-forge
  wtforms                                 3.0.1         pyhd8ed1ab_0        conda-forge
  xz                                      5.2.6         h57fd34a_0          conda-forge
  yaml                                    0.2.5         h3422bc3_2          conda-forge
  yarl                                    1.9.2         py310hd125d64_1     conda-forge
  zipp                                    3.17.0        pyhd8ed1ab_0        conda-forge
  zlib                                    1.2.13        h53f4e23_5          conda-forge
  zstd                                    1.5.5         h4f39d0f_0          conda-forge
```

### Environment info

```shell
❯ micromamba info                                                                                                                  (airflow310) 

       libmamba version : 1.5.1
     micromamba version : 1.5.1
           curl version : libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0
     libarchive version : libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8
       envs directories : /Users/juan_cano/.micromamba/envs
          package cache : /Users/juan_cano/.micromamba/pkgs
                          /Users/juan_cano/.mamba/pkgs
            environment : airflow310 (active)
           env location : /Users/juan_cano/.micromamba/envs/airflow310
      user config files : /Users/juan_cano/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __osx=13.6=0
                          __archspec=1=arm64
               channels : 
       base environment : /Users/juan_cano/.micromamba
               platform : osx-arm64
```

**Comment by xylar** [comment]
@astrojuanlu, I think that is probably something to report upstream to 
https://github.com/apache/airflow/issues
They don't have any constraint on httpx:
https://github.com/apache/airflow/blob/2.7.2/setup.cfg#L105
It wouldn't be a good idea if we start adding constraints here on conda-forge that don't match the upstream package unless the reason for it is specific to conda-forge.

**Comment by xylar** [comment]
@astrojuanlu, I just noticed the downgrade of `httpcore`.  That may very well be the problem, and it may be conda-forge specific.  I'll look into it and try to fix httpx if I can.

**Comment by xylar** [comment]
@astrojuanlu, I looked into this further.  `HTTPTransport` was added to httpx in 0.17.0:
https://github.com/encode/httpx/releases/tag/0.17.0
So this is unrelated to `httpcore` and it seems to be a problem that should be reported upstream as I suggested above.  I will put this constraint here with a note, though.

**Comment by xylar** [comment]
@astrojuanlu, one more update on this.  I think the issue is maybe with conda-forge's version of `dnspython`.  The stack trace you posted seems to suggest that's where the call to `httpx` is originating from.  I will see if I can fix things there.  I likely won't merge #122 unless I can't fix things elsewhere.

**Comment by xylar** [comment]
Okay, I think the problem was that `httpcore` and `httpx` were unconstrained in https://github.com/conda-forge/dnspython-feedstock/pull/13

I have now constrained both in:
https://github.com/conda-forge/dnspython-feedstock/pull/14

If that doesn't take care of the problem, I will need to patch the old build, too.

**Comment by xylar** [comment]
@astrojuanlu, sorry this has been all over the place.  I believe it is solved now.  I ran:
```
mamba create -y -n test python=3.10 airflow
```
I now see:
```
$ mamba list -n test httpx
# packages in environment at /home/xylar/mambaforge/envs/test:
#
# Name                    Version                   Build  Channel
httpx                     0.25.0             pyhd8ed1ab_0    conda-forge
$ mamba list -n test dnspython
# packages in environment at /home/xylar/mambaforge/envs/test:
#
# Name                    Version                   Build  Channel
dnspython                 2.4.2              pyhd8ed1ab_1    conda-forge
```

**Comment by astrojuanlu** [comment]
Thanks for the blazing fast response! For consistency I can check again on macOS tomorrow, but at least on Linux I tried the same commands and I get proper versions of everything now 👍🏽

**Comment by xylar** [comment]
Let me know if this worked on OSX, too.

**Comment by astrojuanlu** [comment]
I confirm it works 👍🏽 Thanks again!
