### ISSUE TITLE
Pendulum 3 causing issues for airflow <= 2.7.2

### ISSUE THREAD

**Issue by xylar** [conda-forge/airflow-feedstock#127]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/site-packages/airflow/settings.py", line 55, in <module>
    TIMEZONE = pendulum.tz.timezone(tz)
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/test_tmp/run_test.py", line 2, in <module>
    import airflow.providers.dbt.cloud
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/site-packages/airflow/__init__.py", line 52, in <module>
    from airflow import configuration, settings
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/site-packages/airflow/configuration.py", line 2340, in <module>
    secrets_backend_list = initialize_secrets_backends()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/site-packages/airflow/configuration.py", line 2254, in initialize_secrets_backends
    secrets_backend_cls = import_string(class_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/site-packages/airflow/utils/module_loading.py", line 37, in import_string
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/site-packages/airflow/secrets/metastore.py", line 29, in <module>
    from airflow.utils.session import NEW_SESSION, provide_session
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/site-packages/airflow/utils/session.py", line 24, in <module>
    from airflow import settings
  File "/home/conda/feedstock_root/build_artifacts/apache-airflow-providers-dbt-cloud_1706649418665/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/site-packages/airflow/settings.py", line 57, in <module>
    TIMEZONE = pendulum.tz.timezone("UTC")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
```

### Installed packages

```shell
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=867404&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3
```

### Environment info

```shell
N/A
```

**Comment by xylar** [comment]
Patching to fix this in:
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/647
